export type Lang="es"|"ak"|"is"|"ks"|"ms"|"os"|"ps"|"ss"|"tr"|"ur"|"sk"|"oc"|"tk"|"ik"|"uz"|"as"|"cs"|"bs"|"fr"|"hr"|"kr"|"ab"|"dz"|"or"|"hz"|"sr"|"zu"|"oj"|"lb"|"nb"|"az"|"fj"|"ar"|"br"|"cr"|"my"|"ky"|"bi"|"ca"|"ba"|"aa"|"ga"|"fa"|"zh"|"da"|"ka"|"ja"|"ia"|"ha"|"ay"|"na"|"si"|"la"|"ii"|"hi"|"fi"|"mi"|"li"|"ki"|"ta"|"bh"|"ch"|"ts"|"th"|"mh"|"bo"|"co"|"rw"|"za"|"kw"|"bg"|"ny"|"lg"|"kg"|"ng"|"mg"|"no"|"ml"|"xh"|"ig"|"tg"|"io"|"lo"|"ko"|"fo"|"eo"|"ho"|"wo"|"an"|"bn"|"wa"|"jv"|"cv"|"dv"|"vo"|"vi"|"yi"|"uk"|"ug"|"ff"|"kv"|"lv"|"af"|"nv"|"tl"|"rn"|"sn"|"tn"|"mn"|"nn"|"tw"|"so"|"to"|"ty"|"av"|"ln"|"en"|"ti"|"gn"|"sg"|"sw"|"iu"|"bm"|"am"|"sv"|"eu"|"su"|"cu"|"ru"|"ee"|"de"|"ce"|"be"|"ae"|"lu"|"ku"|"ne"|"sm"|"rm"|"st"|"sq"|"ie"|"he"|"tt"|"ve"|"km"|"te"|"se"|"gv"|"sc"|"sa"|"ro"|"it"|"qu"|"kj"|"ht"|"et"|"kk"|"pi"|"pa"|"om"|"yo"|"nr"|"pt"|"mt"|"mk"|"mr"|"lt"|"sl"|"nd"|"kn"|"hy"|"id"|"pl"|"gd"|"nl"|"kl"|"hu"|"sd"|"gu"|"gl"|"fy"|"el"|"cy" return{--- 스페인어 - Español
["Spanish"]="es",
--- 아칸어 - Akan
["Akan"]="ak",
--- 아이슬란드어 - Íslenska
["Icelandic"]="is",
--- 카슈미르어 - कश्मीरी, كشميري‎
["Kashmiri"]="ks",
--- 말레이어 - bahasa Melayu, بهاس ملايو‎
["Malay"]="ms",
--- 오세트어 - ирон æвзаг
["Ossetian, Ossetic"]="os",
--- 파슈토어 - پښتو
["Pashto, Pushto"]="ps",
--- 시스와티어 - SiSwati
["Swati"]="ss",
--- 터키어 - Türkçe
["Turkish"]="tr",
--- 우르두어 - اردو
["Urdu"]="ur",
--- 슬로바키아어 - slovenčina, slovenský jazyk
["Slovak"]="sk",
--- 오크어 - occitan, lenga d'òc
["Occitan"]="oc",
--- 투르크멘어 - Türkmen, Түркмен
["Turkmen"]="tk",
--- 이누피아크어 - Iñupiaq, Iñupiatun
["Inupiaq"]="ik",
--- 우즈베크어 - Oʻzbek, Ўзбек, أۇزبېك‎
["Uzbek"]="uz",
--- 아샘어 - অসমীয়া
["Assamese"]="as",
--- 체코어 - čeština, český jazyk
["Czech"]="cs",
--- 보스니아어 - bosanski jezik
["Bosnian"]="bs",
--- 프랑스어 - français, langue française
["French"]="fr",
--- 크로아티아어 - hrvatski jezik
["Croatian"]="hr",
--- 칸누리어 - Kanuri
["Kanuri"]="kr",
--- 압카즈어 - аҧсуа бызшәа, аҧсшәа
["Abkhaz"]="ab",
--- 종카어 - རྫོང་ཁ
["Dzongkha"]="dz",
--- 오리야어 - ଓଡ଼ିଆ
["Oriya"]="or",
--- 헤레로어 - Otjiherero
["Herero"]="hz",
--- 세르비아어 - српски језик
["Serbian"]="sr",
--- 줄루어 - isiZulu
["Zulu"]="zu",
--- 오지브웨이어 - ᐊᓂᔑᓈᐯᒧᐎᓐ
["Ojibwe, Ojibwa"]="oj",
--- 룩셈부르크어 - Lëtzebuergesch
["Luxembourgish, Letzeburgesch"]="lb",
--- 노르웨이어(보크말) - Norsk bokmål
["Norwegian Bokmål"]="nb",
--- 아제르바이잔어 - azərbaycan dili
["Azerbaijani"]="az",
--- 피지어 - vosa Vakaviti
["Fijian"]="fj",
--- 아랍어 - العربية
["Arabic"]="ar",
--- 브르타뉴어 - brezhoneg
["Breton"]="br",
--- 크리어 - ᓀᐦᐃᔭᐍᐏᐣ
["Cree"]="cr",
--- 버마어 - ဗမာစာ
["Burmese"]="my",
--- 키르기스어 - Кыргызча, Кыргыз тили
["Kyrgyz"]="ky",
--- 비슬라마어 - Bislama
["Bislama"]="bi",
--- 카탈로니아어 - català
["Catalan"]="ca",
--- 바슈키르어 - башҡорт теле
["Bashkir"]="ba",
--- 아파르어 - Afaraf
["Afar"]="aa",
--- 아일랜드어 - Gaeilge
["Irish"]="ga",
--- 페르시아어 - فارسی
["Persian (Farsi)"]="fa",
--- 중국어 - 中文 (Zhōngwén), 汉语, 漢語
["Chinese"]="zh",
--- 덴마크어 - dansk
["Danish"]="da",
--- 조지아어 - ქართული
["Georgian"]="ka",
--- 일본어 - 日本語 (にほんご)
["Japanese"]="ja",
--- 인테르링구아 (국제보조어협회) - Interlingua
["Interlingua"]="ia",
--- 하우사어 - (Hausa) هَوُسَ
["Hausa"]="ha",
--- 아이마라어 - aymar aru
["Aymara"]="ay",
--- 나우루어 - Dorerin Naoero
["Nauruan"]="na",
--- 스리랑카어 - සිංහල
["Sinhalese, Sinhala"]="si",
--- 라틴어 - latine, lingua latina
["Latin"]="la",
--- 쓰촨 이어 - ꆈꌠ꒿ Nuosuhxop
["Nuosu"]="ii",
--- 힌디어 - हिन्दी, हिंदी
["Hindi"]="hi",
--- 핀란드어 - suomi, suomen kieli
["Finnish"]="fi",
--- 마오리어 - te reo Māori
["Māori"]="mi",
--- 림버거어 - Limburgs
["Limburgish, Limburgan, Limburger"]="li",
--- 키쿠유어 - Gĩkũyũ
["Kikuyu, Gikuyu"]="ki",
--- 타밀어 - தமிழ்
["Tamil"]="ta",
--- Bihari - भोजपुरी
["Bihari"]="bh",
--- 차모로어 - Chamoru
["Chamorro"]="ch",
--- 총가어 - Xitsonga
["Tsonga"]="ts",
--- 태국어 - ไทย
["Thai"]="th",
--- 마셜제도어 - Kajin M̧ajeļ
["Marshallese"]="mh",
--- 티베트어 - བོད་ཡིག
["Tibetan Standard, Tibetan, Central"]="bo",
--- 코르시카어 - corsu, lingua corsa
["Corsican"]="co",
--- 르완다어 - Ikinyarwanda
["Kinyarwanda"]="rw",
--- 주앙어 - Saɯ cueŋƅ, Saw cuengh
["Zhuang, Chuang"]="za",
--- 콘월어 - Kernewek
["Cornish"]="kw",
--- 불가리아어 - български език
["Bulgarian"]="bg",
--- 니안자어; 치츄어; 츄어 - chiCheŵa, chinyanja
["Chichewa, Chewa, Nyanja"]="ny",
--- 간다어 - Luganda
["Ganda"]="lg",
--- 콩고어 - Kikongo
["Kongo"]="kg",
--- 느동가어 - Owambo
["Ndonga"]="ng",
--- 말라가시어 - fiteny malagasy
["Malagasy"]="mg",
--- 노르웨이어 - Norsk
["Norwegian"]="no",
--- 말라얄람어 - മലയാളം
["Malayalam"]="ml",
--- 코사어 - isiXhosa
["Xhosa"]="xh",
--- 이그보어 - Asụsụ Igbo
["Igbo"]="ig",
--- 타지크어 - тоҷикӣ, toçikī, تاجیکی‎
["Tajik"]="tg",
--- 이도어 - Ido
["Ido"]="io",
--- 라오어 - ພາສາລາວ
["Lao"]="lo",
--- 한국어 - 한국어
["Korean"]="ko",
--- 페로어 - føroyskt
["Faroese"]="fo",
--- 에스페란토어 - Esperanto
["Esperanto"]="eo",
--- 히리 모투어 - Hiri Motu
["Hiri Motu"]="ho",
--- 올로프어 - Wollof
["Wolof"]="wo",
--- 아라곤어 - aragonés
["Aragonese"]="an",
--- 벵골어 - বাংলা
["Bengali, Bangla"]="bn",
--- 왈론어 - walon
["Walloon"]="wa",
--- 자바어 - ꦧꦱꦗꦮ, Basa Jawa
["Javanese"]="jv",
--- 추바시어 - чӑваш чӗлхи
["Chuvash"]="cv",
--- 디베히어 - ދިވެހި
["Divehi, Dhivehi, Maldivian"]="dv",
--- 볼라퓌크어 - Volapük
["Volapük"]="vo",
--- 베트남어 - Tiếng Việt
["Vietnamese"]="vi",
--- 이디시어 - ייִדיש
["Yiddish"]="yi",
--- 우크라이나어 - Українська
["Ukrainian"]="uk",
--- 위구르어 - ئۇيغۇرچە‎, Uyghurche
["Uyghur"]="ug",
--- 풀라어 - Fulfulde, Pulaar, Pular
["Fula, Fulah, Pulaar, Pular"]="ff",
--- 코미어 - коми кыв
["Komi"]="kv",
--- 라트비아어 - latviešu valoda
["Latvian"]="lv",
--- 아프리칸스어 - Afrikaans
["Afrikaans"]="af",
--- 나바호어 - Diné bizaad
["Navajo, Navaho"]="nv",
--- 타갈로그어 - Wikang Tagalog
["Tagalog"]="tl",
--- 룬디어 - Ikirundi
["Kirundi"]="rn",
--- 쇼나어 - chiShona
["Shona"]="sn",
--- 세츠와나어 - Setswana
["Tswana"]="tn",
--- 몽고어 - Монгол хэл
["Mongolian"]="mn",
--- 노르웨이어(니노르스크) - Norsk nynorsk
["Norwegian Nynorsk"]="nn",
--- 트위어 - Twi
["Twi"]="tw",
--- 소말리아어 - Soomaaliga, af Soomaali
["Somali"]="so",
--- 통가어 - faka Tonga
["Tonga (Tonga Islands)"]="to",
--- 타히티어 - Reo Tahiti
["Tahitian"]="ty",
--- 아바릭어 - авар мацӀ, магӀарул мацӀ
["Avaric"]="av",
--- 링갈라어 - Lingála
["Lingala"]="ln",
--- 영어 - English
["English"]="en",
--- 티그리냐어 - ትግርኛ
["Tigrinya"]="ti",
--- 과라니어 - Avañe'ẽ
["Guaraní"]="gn",
--- 산고어 - yângâ tî sängö
["Sango"]="sg",
--- 스와힐리어 - Kiswahili
["Swahili"]="sw",
--- 이눅티투트어 - ᐃᓄᒃᑎᑐᑦ
["Inuktitut"]="iu",
--- 밤바라어 - bamanankan
["Bambara"]="bm",
--- 암하라어 - አማርኛ
["Amharic"]="am",
--- 스웨덴어 - svenska
["Swedish"]="sv",
--- 바스크어 - euskara, euskera
["Basque"]="eu",
--- 순다어 - Basa Sunda
["Sundanese"]="su",
--- 교회 슬라브어 - ѩзыкъ словѣньскъ
["Old Church Slavonic, Church Slavonic, Old Bulgarian"]="cu",
--- 러시아어 - Русский
["Russian"]="ru",
--- 에웨어 - Eʋegbe
["Ewe"]="ee",
--- 독일어 - Deutsch
["German"]="de",
--- 체첸어 - нохчийн мотт
["Chechen"]="ce",
--- 벨라루스어 - беларуская мова
["Belarusian"]="be",
--- 아베스타어 - avesta
["Avestan"]="ae",
--- 루바-카탄가어 - Tshiluba
["Luba-Katanga"]="lu",
--- 쿠르드어 - Kurdî, كوردی‎
["Kurdish"]="ku",
--- 네팔어 - नेपाली
["Nepali"]="ne",
--- 사모아어 - gagana fa'a Samoa
["Samoan"]="sm",
--- 레토로만어 - rumantsch grischun
["Romansh"]="rm",
--- 소토어 (남부) - Sesotho
["Southern Sotho"]="st",
--- 알바니아어 - Shqip
["Albanian"]="sq",
--- 인테르링구에 - Originally called Occidental; then Interlingue after WWII
["Interlingue"]="ie",
--- 히브리어 - עברית
["Hebrew (modern)"]="he",
--- 타타르어 - татар теле, tatar tele
["Tatar"]="tt",
--- 벤다어 - Tshivenḓa
["Venda"]="ve",
--- 캄보디아어 - ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ
["Khmer"]="km",
--- 텔루구어 - తెలుగు
["Telugu"]="te",
--- 북부 사미어 - Davvisámegiella
["Northern Sami"]="se",
--- 맹크스어 - Gaelg, Gailck
["Manx"]="gv",
--- 사르디니아어 - sardu
["Sardinian"]="sc",
--- 산스크리트어 - संस्कृतम्
["Sanskrit (Saṁskṛta)"]="sa",
--- 루마니아어 - Română
["Romanian"]="ro",
--- 이탈리아어 - Italiano
["Italian"]="it",
--- 케추아어 - Runa Simi, Kichwa
["Quechua"]="qu",
--- 쿠안야마어 - Kuanyama
["Kwanyama, Kuanyama"]="kj",
--- 아이티어 - Kreyòl ayisyen
["Haitian, Haitian Creole"]="ht",
--- 에스토니아어 - eesti, eesti keel
["Estonian"]="et",
--- 카자흐어 - қазақ тілі
["Kazakh"]="kk",
--- 팔리어 - पाऴि
["Pāli"]="pi",
--- 펀잡어 - ਪੰਜਾਬੀ
["(Eastern) Punjabi"]="pa",
--- 오로모어 - Afaan Oromoo
["Oromo"]="om",
--- 요루바어 - Yorùbá
["Yoruba"]="yo",
--- 남부 은데벨레어 - isiNdebele
["Southern Ndebele"]="nr",
--- 포르투갈어 - Português
["Portuguese"]="pt",
--- 몰타어 - Malti
["Maltese"]="mt",
--- 마케도니아어 - македонски јазик
["Macedonian"]="mk",
--- 마라티어 - मराठी
["Marathi (Marāṭhī)"]="mr",
--- 리투아니아어 - lietuvių kalba
["Lithuanian"]="lt",
--- 슬로베니아어 - slovenski jezik, slovenščina
["Slovene"]="sl",
--- 북부 은데벨레어 - isiNdebele
["Northern Ndebele"]="nd",
--- 칸나다어 - ಕನ್ನಡ
["Kannada"]="kn",
--- 아르메니아어 - Հայերեն
["Armenian"]="hy",
--- 인도네시아어 - Bahasa Indonesia
["Indonesian"]="id",
--- 폴란드어 - język polski, polszczyzna
["Polish"]="pl",
--- 스코틀랜드 게일어 - Gàidhlig
["Scottish Gaelic, Gaelic"]="gd",
--- 네덜란드어 - Nederlands, Vlaams
["Dutch"]="nl",
--- 그린란드어 - kalaallisut, kalaallit oqaasii
["Kalaallisut, Greenlandic"]="kl",
--- 헝가리어 - magyar
["Hungarian"]="hu",
--- 신디어 - सिन्धी, سنڌي، سندھی‎
["Sindhi"]="sd",
--- 구자라트어 - ગુજરાતી
["Gujarati"]="gu",
--- 갈리시아어 - galego
["Galician"]="gl",
--- 프리지아어 - Frysk
["Western Frisian"]="fy",
--- 그리스어 - ελληνικά
["Greek (modern)"]="el",
--- 웨일스어 - Cymraeg
["Welsh"]="cy",
}